version: 0.0
os: linux
files:
    - source: /
      destination: /var/www/ftv-api
hooks:
    ApplicationStop:
        - location: scripts/stop_server.sh
          timeout: 500
          runas: ubuntu
    AfterInstall:
        - location: scripts/install_dependencies.sh
          timeout: 500
          runas: ubuntu
    ApplicationStart:
        - location: scripts/start_server.sh
          timeout: 500
          runas: ubuntu
