# wallet api pipeline configuration for aws codedeploy
# by - agent441

image: atlassian/default-image:2

pipelines:
    branches:
        develop:
            - step:
                  name: Build
                  script:
                      - zip -r api.zip *
                  artifacts:
                      - api.zip
            - step:
                  name: Upload to S3
                  services:
                      - docker
                  script:
                      - pipe: atlassian/aws-code-deploy:0.3.2
                        variables:
                            AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                            AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                            AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                            S3_BUCKET: $S3_BUCKET
                            COMMAND: "upload"
                            APPLICATION_NAME: $APPLICATION_NAME
                            ZIP_FILE: "api.zip"
            - step:
                  name: Deploy with CodeDeploy
                  services:
                      - docker
                  script:
                      - echo "Environment ${REPOSITORY_VARIABLE}"
                      - pipe: atlassian/aws-code-deploy:0.3.2
                        variables:
                            AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                            AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                            AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                            S3_BUCKET: $S3_BUCKET
                            COMMAND: "deploy"
                            APPLICATION_NAME: $APPLICATION_NAME
                            DEPLOYMENT_GROUP: $DEPLOYMENT_GROUP
                            IGNORE_APPLICATION_STOP_FAILURES: "true"
                            FILE_EXISTS_BEHAVIOR: "OVERWRITE"
                            WAIT: "true"
